### ISSUE TITLE
Failed to get sink information: No such entity

### ISSUE THREAD

**Issue by ayush391** [siddhpant/broo#10]
I am on the latest manjaro kde with Pulseaudio. I modified the script to install mumble and murmur through pacman. But I am still getting this error, Please help.

**Comment by siddhpant** [comment]
> I modified the script to install mumble and murmur through pacman.

Fixed setup crashing in [48e2dd8](https://github.com/siddhpant/broo/commit/48e2dd8e66ece61922fa7671c4a23a063087d21c) due to malformed if statement.

The expected behaviour was to ignore installation on non-apt systems. So you needn't change the setup file now.

> But I am still getting this error, Please help.

Can you add an `echo "here"` on start of `get_mumble_sink_input_index()`, so that we know where the crash is happening?

**Comment by ayush391** [comment]
I cloned the new script and added the echo statement. I did not modify anything else.
![image](https://user-images.githubusercontent.com/67093911/187906378-3ddfe5a0-aa60-45bc-b9a8-61cb7dc2b6bd.png)

**Comment by siddhpant** [comment]
Add `pactl list short sinks` on start of `configure_sink()` and send the output.

**Comment by ayush391** [comment]
Here you go

![image](https://user-images.githubusercontent.com/67093911/187908341-d3b0d808-02ba-4454-b448-c73561b3a56c.png)

**Comment by siddhpant** [comment]
Fixed. Please update.

**Comment by siddhpant** [comment]
Did it?

**Comment by ayush391** [comment]
Nope. 
![image](https://user-images.githubusercontent.com/67093911/188840023-9813c663-edce-4536-8185-9cf7d81ee320.png)

**Comment by ayush391** [comment]
bro actually i forgot to update the script 😅 . But it still showing some error.
![image](https://user-images.githubusercontent.com/67093911/188841619-8e0c6070-4113-41d5-9152-58cacf39a701.png)

**Comment by siddhpant** [comment]
hmm

**Comment by siddhpant** [comment]
Ok I should have just said this before:

Please add `set -x` at the top of the script so it shows every command.

**Comment by ayush391** [comment]
omg its working now. Thanks broo 👊

**Comment by ayush391** [comment]
the script ran succesfully as it showed the IP address of the mumble server. But I noticed that there is no input device 'Monitor over number ' in my system. There is just one output device added 'broo'. I just restarted my system and the script is the showing the same error message again. :(
![image](https://user-images.githubusercontent.com/67093911/188848474-5ec49ed6-a179-4b1b-becb-f5f9d8caf89b.png)

**Comment by siddhpant** [comment]
https://bbs.archlinux.org/viewtopic.php?id=225441

**Comment by siddhpant** [comment]
Ping...

Will be closing the issue if no reply in 7 days, as it seems to be a pactl issue.

**Comment by siddhpant** [comment]
#23 probably describes the same problem.

**Comment by CodeShakingSheep** [comment]
Coming from #23 . Just to give you my specs: I'm running **PulseAudio on Ubuntu 22.04**. I added `set -x` at the top of the script. This is the output:

```
Initialising Broo...

+ start_mumble_server
++ command -v mumble-server
+ [[ -n /usr/local/bin/mumble-server ]]
+ echo 17593
+ sleep 3
+ nohup mumble-server -ini /home/<REDACTED_USER>/.config/broo/murmur.ini -fg
+ start_mumble_client
+ [[ -f /home/<REDACTED_USER>/.config/broo/no_offscreen ]]
+ echo 17597
+ nohup mumble mumble://127.0.0.1 ' '
+ grep --line-buffered -q 'ServerHandler: TLS cipher'
+ tail -f /var/run/user/1000/broo/mumble_client.out
++ pactl info
++ grep '^Server Name'
+ [[ Server Name: pulseaudio =~ PipeWire ]]
+ add_mic_pulseaudio
++ pactl load-module module-null-sink sink_name=Broo sink_properties=device.description=Broo
+ pa_index=30
+ echo 30
+ sleep 3
+ '[' -f /home/<REDACTED_USER>/.config/asound.state ']'
+ configure_sink
+ pactl set-sink-volume Broo 0
++ pactl get-default-sink
+ default_sink=alsa_output.pci-0000_00_1f.3.analog-stereo
+ pactl set-default-source Broo
Failure: No such entity
```

This is the output of `pactl list short sinks`
```
1	alsa_output.pci-0000_00_1f.3.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
5	Broo	module-null-sink.c	s16le 2ch 44100Hz	SUSPENDED
```

This is the output of `pactl list sink-inputs`
```
Sink Input #80
	Driver: protocol-native.c
	Owner Module: 10
	Client: 17
	Sink: 1
	Sample Specification: s16le 1ch 44100Hz
	Channel Map: mono
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "1"  format.channel_map = "\"mono\""
	Corked: no
	Mute: no
	Volume: mono: 65536 / 100% / 0.00 dB
	        balance 0.00
	Buffer Latency: 0 usec
	Sink Latency: 4119 usec
	Resample method: copy
	Properties:
		media.name = "playback"
		application.name = "speech-dispatcher-dummy"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "16366"
		application.process.user = "<REDACTED_USER>"
		application.process.host = "<REDACTED_HOST>"
		application.process.binary = "sd_dummy"
		application.language = "C"
		window.x11.display = ":0"
		application.process.machine_id = "9638ecc236204733b0cb7c66ac7682d7"
		module-stream-restore.id = "sink-input-by-application-name:speech-dispatcher-dummy"

Sink Input #91
	Driver: protocol-native.c
	Owner Module: 10
	Client: 47
	Sink: 1
	Sample Specification: s16le 2ch 48000Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = "\"s16le\""  format.rate = "48000"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Corked: no
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Buffer Latency: 32783 usec
	Sink Latency: 3949 usec
	Resample method: speex-float-1
	Properties:
		media.name = "Mumble Speakers"
		application.name = "Mumble"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.id = "net.sourceforge.mumble.mumble"
		application.icon_name = "mumble"
		media.role = "game"
		application.process.id = "17597"
		application.process.user = "<REDACTED_USER>"
		application.process.host = "<REDACTED_HOST>"
		application.process.binary = "mumble"
		application.language = "C.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "9638ecc236204733b0cb7c66ac7682d7"
		module-stream-restore.id = "sink-input-by-media-role:game"
```

This is the output of `ps -aux | grep mumble`.
```
<REDACTED_USER>         17593  0.0  0.1 165100 29788 pts/0    Sl   11:46   0:00 mumble-server -ini /home/<REDACTED_USER>/.config/broo/murmur.ini -fg
<REDACTED_USER>         17597  5.3  0.8 2539524 145256 pts/0  Sl   11:46   0:26 mumble mumble://127.0.0.1  
<REDACTED_USER>         19303  0.0  0.0  11756  2432 pts/0    S+   11:54   0:00 grep --color=auto mumble
```

In pavucontrol Mumble is visible in Playback and Recording.
![image](https://github.com/user-attachments/assets/82e3b894-f078-4e56-9a4f-177bddcbc552)
![image](https://github.com/user-attachments/assets/07bb38e1-7573-4b57-a5fb-385012116e83)


Any idea how I can fix this issue? Thanks.

**Comment by siddhpant** [comment]
> pactl set-default-source Broo
> Failure: No such entity

Oops 🤦🏻‍♂️ Recent change removed the `.monitor` needed which I added earlier in this thread.

Can you try `git revert HEAD~1` and run `./broo`?

**Comment by CodeShakingSheep** [comment]
Alright, reverted the commit and now the error is gone :laughing: 
```
Do you want to start Broo, or close it? (s/c): s

Initialising Broo...

Done! Use "Monitor of Broo" as your input mic, and enjoy!

Connect to Broo's server on <REDACTED_IP_ADDRESS> :)
```

However, I still have `Broo` as Output Device and I can't select `Monitor of Broo` as Input Device in Ubuntu sound settings.
![image](https://github.com/user-attachments/assets/edc92bbc-0a5a-47b6-b326-4d317d7c927e)
![image](https://github.com/user-attachments/assets/0e093995-9fc9-42d5-bfec-f72709775ae2)

This is how Input Devices look like in pavucontrol:
![image](https://github.com/user-attachments/assets/6e12f664-c48b-4b1a-87f0-3a14af6e220c)

My goal is to use Broo in a video meeting (particularly Jitsi Meet Desktop app) and this isn't working ad I cannot select `Broo` or `Monitor of Broo` as microphone.
![image](https://github.com/user-attachments/assets/f089b03d-1253-4a37-9b02-211d858309e2)

**Comment by siddhpant** [comment]
Hmm, can you use "Monitor of Broo" in some other apps, like Firefox or Discord?

**Comment by siddhpant** [comment]
Closing this issue as you don't face the original one (so it was just OP with an arch moment).

**Comment by CodeShakingSheep** [comment]
> Hmm, can you use "Monitor of Broo" in some other apps, like Firefox or Discord? Can you try easyeffects as a workaround?
> 
> Also, please have a look at #15.

I don't have Discord installed. In Firefox I can use "Monitor of Broo" as microphone but in Brave (fork of Chrome) I can't. Is that normal? I'll check out easyeffects.

**Comment by siddhpant** [comment]
> In Firefox I can use "Monitor of Broo" as microphone but in Brave (fork of Chrome) I can't. Is that normal?

No it's not. Not sure why this happens. Is it the same on chromium?

> I suppose that's because it only works with pipewire and I'm on pulseaudio.

Oops yeah, sorry.

> There I can see "Mumble Microphone" but when I activate it it only appears in the output devices as well. Any idea about that?

Does it show up on the app?

I would avoid testing with gnome settings and rather check Firefox etc. first. The settings page is broken and doesn't show any monitor input idk why, so its output is misleading. Pulseaudio is just broken in this regards.

Anyways, can you try this? -> https://unix.stackexchange.com/a/620178

If it works, I can add it in the script.

Can we change the input source from pavucontrol?

**Comment by CodeShakingSheep** [comment]
I just executed your command, tested it and it's working. I can now see Broo as microphone in my app. That's awesome!

![Screenshot from 2024-09-26 19-40-16](https://github.com/user-attachments/assets/db86bafe-79f2-4b2f-8cdf-39223db161c9)]

However, I would suggest to name it `Broo mic` or something similar. Would appreciate if you could add this to the script :pray:
